FROM node:24-alpine-slim AS builder
WORKDIR /app
COPY ../frontend/package*.json ./
RUN npm ci

COPY ../frontend ./
RUN npm run build

FROM nginx:alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
