include:
  - compose/services.yml
  - compose/mirror.yml
  - compose/databases.yml
  - compose/devtools.yml

volumes:
  postgres_primary_data:
  postgres_replica_data:
  minio_data:
  redis_data:

  loki_data:
  grafana_data:

networks:
  backend:
    driver: bridge