CREATE ROLE app_rw LOGIN PASSWORD 'app_rw_pass';
CREATE ROLE app_ro LOGIN PASSWORD 'app_ro_pass';

GRANT ALL PRIVILEGES ON DATABASE orpheon TO app_rw;

GRANT CONNECT ON DATABASE orpheon TO app_ro;
GRANT USAGE ON SCHEMA public TO app_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO app_ro;