openapi: 3.2.0
info:
  title: Auth API
  version: "2.0.0"
servers:
  - url: /api/v2
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        "200":
          description: Tokens set in cookies
        "400":
          description: Invalid request
        "500":
          description: Internal server error

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        "200":
          description: Tokens set in cookies
        "400":
          description: Invalid request
        "401":
          description: Unauthorized

  /auth/refresh:
    post:
      summary: Refresh JWT tokens
      responses:
        "200":
          description: Tokens refreshed
        "401":
          description: Unauthorized

  /auth/logout:
    post:
      summary: Logout user
      responses:
        "200":
          description: User logged out

  /auth/password/update:
    post:
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPasswords'
      responses:
        "200":
          description: Password updated
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

components:
  schemas:
    UserCredentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - email
        - password

    UserPasswords:
      type: object
      properties:
        old_password:
          type: string
          format: password
        new_password:
          type: string
          format: password
      required:
        - old_password
        - new_password
