proxy_cache off;

auth_request /_auth_optional;
auth_request_set $user_id $upstream_http_x_user_id;
auth_request_set $access_level $upstream_http_x_access_level;

proxy_set_header X-User-Id $user_id;
proxy_set_header X-Access-Level $access_level;