set $no_cache 0;
if ($request_method != GET) {
    set $no_cache 1;
}
if ($request_uri ~ ^/api) {
    set $no_cache 1;
}

proxy_cache public_api;
proxy_buffering on;
proxy_no_cache $no_cache;
proxy_cache_bypass $no_cache;

# proxy_ignore_headers Expires;
# proxy_ignore_headers Set-Cookie;
# proxy_ignore_headers Cache-Control;

# proxy_hide_header Expires;
# proxy_hide_header Cache-Control;
# proxy_hide_header Set-Cookie;
# proxy_hide_header Pragma;

proxy_cache_key "$scheme$request_method$host$request_uri$is_args$args";
proxy_cache_methods GET HEAD;
proxy_cache_use_stale error timeout updating 
                        http_500 http_502 http_503 http_504;
proxy_cache_valid 200 302 304 1h;
proxy_cache_valid 404 1m;

add_header X-Cache-Status $upstream_cache_status;
