
location /api/v1/auth {
    include /etc/nginx/conf.d/proxy/auth.conf;

    add_header X-Debug-Upstream $upstream_server_name always;

    limit_except GET {
        proxy_pass http://auth_msv${mirror};
    }
    proxy_pass http://auth_msv_get${mirror};
}

location /api/v1/users {
    include /etc/nginx/conf.d/proxy/auth.conf;

    add_header X-Debug-Upstream $upstream_server_name always;

    limit_except GET {
        proxy_pass http://user_msv${mirror};
    }
    proxy_pass http://user_msv_get${mirror};
}

location ~ ^/api/v1/(albums|tracks|artists|playlists|favorites|genres|licenses)(/|$) {
    include /etc/nginx/conf.d/proxy/auth.conf;

    add_header X-Debug-Upstream $upstream_server_name always;

    limit_except GET {
        proxy_pass http://content_msv${mirror};
    }
    proxy_pass http://content_msv_get${mirror};
}
