location = /_auth_optional {
    internal;
    proxy_pass http://auth_msv${mirror}/api/v1/auth/claims;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";

    proxy_set_header Cookie $http_cookie;
    proxy_set_header Authorization $http_authorization;

    # ignoring error
    proxy_intercept_errors on;
    error_page 401 403 =204 /_auth_optional_noop;
}

location = /_auth_optional_noop {
    internal;
    return 204;
}

location /api/v1/auth {
    include /etc/nginx/conf.d/proxy/proxy.conf;

    add_header X-Debug-Upstream $upstream_server_name always;

    limit_except GET {
        proxy_pass http://auth_msv${mirror};
    }
    proxy_pass http://auth_msv_get${mirror};
}

location /api/v1/users {
    include /etc/nginx/conf.d/proxy/proxy.conf;

    add_header X-Debug-Upstream $upstream_server_name always;

    limit_except GET {
        proxy_pass http://user_msv${mirror};
    }
    proxy_pass http://user_msv_get${mirror};
}

location ~ ^/api/v1/(albums|tracks|artists|playlists|favorites|genres|licenses)(/|$) {
    include /etc/nginx/conf.d/proxy/proxy.conf;

    add_header X-Debug-Upstream $upstream_server_name always;

    limit_except GET {
        proxy_pass http://content_msv${mirror};
    }
    proxy_pass http://content_msv_get${mirror};
}
