# location = /_auth {
#     internal;
#     proxy_pass http://auth_msv${mirror}/api/v1/auth/claims;
#     proxy_pass_request_body off;
#     proxy_set_header Content-Length "";
#     proxy_set_header Cookie $http_cookie;
# }

location = /_auth_optional {
    internal;
    proxy_pass http://auth_msv${mirror}/api/v1/auth/claims;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";

    proxy_set_header Cookie $http_cookie;
    proxy_set_header Authorization $http_authorization;

    # ignoring error
    proxy_intercept_errors on;
    error_page 401 403 =204 /_auth_optional_noop;
}

location = /_auth_optional_noop {
    internal;
    return 204;
}
