worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;

    proxy_cache_path /var/cache/nginx/proxy_cache levels=1:2 
                     keys_zone=public_api:100m 
                     max_size=1g 
                     inactive=24h 
                     use_temp_path=off;
    open_file_cache max=10000 inactive=5m;
    open_file_cache_valid 60s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    include /etc/nginx/conf.d/*.conf;
}
