// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/hahaclassic/orpheon/backend/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistPolicyService is an autogenerated mock type for the PlaylistPolicyService type
type PlaylistPolicyService struct {
	mock.Mock
}

type PlaylistPolicyService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistPolicyService) EXPECT() *PlaylistPolicyService_Expecter {
	return &PlaylistPolicyService_Expecter{mock: &_m.Mock}
}

// CanDelete provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistPolicyService) CanDelete(ctx context.Context, claims *entities.Claims, playlistID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for CanDelete")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Claims, uuid.UUID) (bool, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Claims, uuid.UUID) bool); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistPolicyService_CanDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanDelete'
type PlaylistPolicyService_CanDelete_Call struct {
	*mock.Call
}

// CanDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entities.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistPolicyService_Expecter) CanDelete(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistPolicyService_CanDelete_Call {
	return &PlaylistPolicyService_CanDelete_Call{Call: _e.mock.On("CanDelete", ctx, claims, playlistID)}
}

func (_c *PlaylistPolicyService_CanDelete_Call) Run(run func(ctx context.Context, claims *entities.Claims, playlistID uuid.UUID)) *PlaylistPolicyService_CanDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistPolicyService_CanDelete_Call) Return(_a0 bool, _a1 error) *PlaylistPolicyService_CanDelete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistPolicyService_CanDelete_Call) RunAndReturn(run func(context.Context, *entities.Claims, uuid.UUID) (bool, error)) *PlaylistPolicyService_CanDelete_Call {
	_c.Call.Return(run)
	return _c
}

// CanEdit provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistPolicyService) CanEdit(ctx context.Context, claims *entities.Claims, playlistID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for CanEdit")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Claims, uuid.UUID) (bool, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Claims, uuid.UUID) bool); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistPolicyService_CanEdit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanEdit'
type PlaylistPolicyService_CanEdit_Call struct {
	*mock.Call
}

// CanEdit is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entities.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistPolicyService_Expecter) CanEdit(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistPolicyService_CanEdit_Call {
	return &PlaylistPolicyService_CanEdit_Call{Call: _e.mock.On("CanEdit", ctx, claims, playlistID)}
}

func (_c *PlaylistPolicyService_CanEdit_Call) Run(run func(ctx context.Context, claims *entities.Claims, playlistID uuid.UUID)) *PlaylistPolicyService_CanEdit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistPolicyService_CanEdit_Call) Return(_a0 bool, _a1 error) *PlaylistPolicyService_CanEdit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistPolicyService_CanEdit_Call) RunAndReturn(run func(context.Context, *entities.Claims, uuid.UUID) (bool, error)) *PlaylistPolicyService_CanEdit_Call {
	_c.Call.Return(run)
	return _c
}

// CanView provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistPolicyService) CanView(ctx context.Context, claims *entities.Claims, playlistID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for CanView")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Claims, uuid.UUID) (bool, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Claims, uuid.UUID) bool); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistPolicyService_CanView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanView'
type PlaylistPolicyService_CanView_Call struct {
	*mock.Call
}

// CanView is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entities.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistPolicyService_Expecter) CanView(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistPolicyService_CanView_Call {
	return &PlaylistPolicyService_CanView_Call{Call: _e.mock.On("CanView", ctx, claims, playlistID)}
}

func (_c *PlaylistPolicyService_CanView_Call) Run(run func(ctx context.Context, claims *entities.Claims, playlistID uuid.UUID)) *PlaylistPolicyService_CanView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistPolicyService_CanView_Call) Return(_a0 bool, _a1 error) *PlaylistPolicyService_CanView_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistPolicyService_CanView_Call) RunAndReturn(run func(context.Context, *entities.Claims, uuid.UUID) (bool, error)) *PlaylistPolicyService_CanView_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistPolicyService creates a new instance of PlaylistPolicyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistPolicyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistPolicyService {
	mock := &PlaylistPolicyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
