syntax = "proto3";

import "google/protobuf/empty.proto";
import "jwt/v1/proto/jwt.proto";

option go_package = "github.com/hahaclassic/orpheon/api/auth-msv/v1/proto";

package auth;

service AuthService {
    rpc RegisterUser (RegisterUserRequest) returns (AuthTokens);
    rpc Login (UserCredentials) returns (AuthTokens);
    rpc RefreshTokens (RefreshToken) returns (AuthTokens);
    rpc Logout (RefreshToken) returns (google.protobuf.Empty); 
    rpc GetClaims (AccessToken) returns (jwt.Claims);

    rpc UpdatePassword (UpdatePasswordRequest) returns (google.protobuf.Empty);
}

message RegisterUserRequest {
    string login = 1;
    string password = 2;
    string username = 3;
}

message UserCredentials {
    string login = 1;
    string password = 2;
}

message AuthTokens {
    string access = 1;
    string refresh = 2;
}

message AccessToken {
    string value = 1;
}

message RefreshToken {
    string value = 1;
}

message UserPasswords {
    string new = 1;
    string old = 2;
}

message UpdatePasswordRequest {
    UserPasswords passwords = 1;
    jwt.Claims claims = 2;
}
