#!/bin/bash

set -e

if [ "$1" == "--help" ]; then 
  echo "goupd: script for updating the golang version 
    
>    goupd [version]

>    example: goupd 1.24.0

1. specify the desired version with the first argument of the script
2. to install the latest version, just run the script without parameters."
  exit 0
fi


# first arg - desired go version
if [ -n "$1" ]; then
  GO_VERSION="$1"
  echo "got version $1"
else
  GO_VERSION=$(curl -s https://go.dev/VERSION?m=text | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
  echo "got latest version ${GO_VERSION}"
fi

GO_TARBALL="go${GO_VERSION}.linux-amd64.tar.gz"
GO_URL="https://go.dev/dl/${GO_TARBALL}"

# deleted previos version
sudo rm -rf /usr/local/go

# install new golang version
wget -q --show-progress "$GO_URL"
sudo tar -C /usr/local -xzf "$GO_TARBALL"
rm "$GO_TARBALL"

if ! grep -q "/usr/local/go/bin" ~/.bashrc; then
  echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
fi

source ~/.bashrc

go version

