// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: common/jwt/v1/proto/jwt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Claims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	AccessLevel   int32                  `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_common_jwt_v1_proto_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_common_jwt_v1_proto_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_common_jwt_v1_proto_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *Claims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Claims) GetAccessLevel() int32 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

var File_common_jwt_v1_proto_jwt_proto protoreflect.FileDescriptor

const file_common_jwt_v1_proto_jwt_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon/jwt/v1/proto/jwt.proto\x12\x03jwt\"D\n" +
	"\x06Claims\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_level\x18\x02 \x01(\x05R\vaccessLevelB8Z6github.com/hahaclassic/orpheon/api/common/jwt/v1/protob\x06proto3"

var (
	file_common_jwt_v1_proto_jwt_proto_rawDescOnce sync.Once
	file_common_jwt_v1_proto_jwt_proto_rawDescData []byte
)

func file_common_jwt_v1_proto_jwt_proto_rawDescGZIP() []byte {
	file_common_jwt_v1_proto_jwt_proto_rawDescOnce.Do(func() {
		file_common_jwt_v1_proto_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_jwt_v1_proto_jwt_proto_rawDesc), len(file_common_jwt_v1_proto_jwt_proto_rawDesc)))
	})
	return file_common_jwt_v1_proto_jwt_proto_rawDescData
}

var file_common_jwt_v1_proto_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_jwt_v1_proto_jwt_proto_goTypes = []any{
	(*Claims)(nil), // 0: jwt.Claims
}
var file_common_jwt_v1_proto_jwt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_jwt_v1_proto_jwt_proto_init() }
func file_common_jwt_v1_proto_jwt_proto_init() {
	if File_common_jwt_v1_proto_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_jwt_v1_proto_jwt_proto_rawDesc), len(file_common_jwt_v1_proto_jwt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_jwt_v1_proto_jwt_proto_goTypes,
		DependencyIndexes: file_common_jwt_v1_proto_jwt_proto_depIdxs,
		MessageInfos:      file_common_jwt_v1_proto_jwt_proto_msgTypes,
	}.Build()
	File_common_jwt_v1_proto_jwt_proto = out.File
	file_common_jwt_v1_proto_jwt_proto_goTypes = nil
	file_common_jwt_v1_proto_jwt_proto_depIdxs = nil
}
