// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ArtistAssignService is an autogenerated mock type for the ArtistAssignService type
type ArtistAssignService struct {
	mock.Mock
}

type ArtistAssignService_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtistAssignService) EXPECT() *ArtistAssignService_Expecter {
	return &ArtistAssignService_Expecter{mock: &_m.Mock}
}

// AssignArtistToAlbum provides a mock function with given fields: ctx, claims, artistID, albumID
func (_m *ArtistAssignService) AssignArtistToAlbum(ctx context.Context, claims *entity.Claims, artistID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, claims, artistID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for AssignArtistToAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, artistID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignService_AssignArtistToAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignArtistToAlbum'
type ArtistAssignService_AssignArtistToAlbum_Call struct {
	*mock.Call
}

// AssignArtistToAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - artistID uuid.UUID
//   - albumID uuid.UUID
func (_e *ArtistAssignService_Expecter) AssignArtistToAlbum(ctx interface{}, claims interface{}, artistID interface{}, albumID interface{}) *ArtistAssignService_AssignArtistToAlbum_Call {
	return &ArtistAssignService_AssignArtistToAlbum_Call{Call: _e.mock.On("AssignArtistToAlbum", ctx, claims, artistID, albumID)}
}

func (_c *ArtistAssignService_AssignArtistToAlbum_Call) Run(run func(ctx context.Context, claims *entity.Claims, artistID uuid.UUID, albumID uuid.UUID)) *ArtistAssignService_AssignArtistToAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignService_AssignArtistToAlbum_Call) Return(_a0 error) *ArtistAssignService_AssignArtistToAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignService_AssignArtistToAlbum_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error) *ArtistAssignService_AssignArtistToAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// AssignArtistToTrack provides a mock function with given fields: ctx, claims, artistID, trackID
func (_m *ArtistAssignService) AssignArtistToTrack(ctx context.Context, claims *entity.Claims, artistID uuid.UUID, trackID uuid.UUID) error {
	ret := _m.Called(ctx, claims, artistID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for AssignArtistToTrack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, artistID, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignService_AssignArtistToTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignArtistToTrack'
type ArtistAssignService_AssignArtistToTrack_Call struct {
	*mock.Call
}

// AssignArtistToTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - artistID uuid.UUID
//   - trackID uuid.UUID
func (_e *ArtistAssignService_Expecter) AssignArtistToTrack(ctx interface{}, claims interface{}, artistID interface{}, trackID interface{}) *ArtistAssignService_AssignArtistToTrack_Call {
	return &ArtistAssignService_AssignArtistToTrack_Call{Call: _e.mock.On("AssignArtistToTrack", ctx, claims, artistID, trackID)}
}

func (_c *ArtistAssignService_AssignArtistToTrack_Call) Run(run func(ctx context.Context, claims *entity.Claims, artistID uuid.UUID, trackID uuid.UUID)) *ArtistAssignService_AssignArtistToTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignService_AssignArtistToTrack_Call) Return(_a0 error) *ArtistAssignService_AssignArtistToTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignService_AssignArtistToTrack_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error) *ArtistAssignService_AssignArtistToTrack_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtistAssignService creates a new instance of ArtistAssignService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistAssignService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistAssignService {
	mock := &ArtistAssignService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
