// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// ArtistAssignRepository is an autogenerated mock type for the ArtistAssignRepository type
type ArtistAssignRepository struct {
	mock.Mock
}

type ArtistAssignRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtistAssignRepository) EXPECT() *ArtistAssignRepository_Expecter {
	return &ArtistAssignRepository_Expecter{mock: &_m.Mock}
}

// AssignArtistToAlbum provides a mock function with given fields: ctx, artistID, albumID
func (_m *ArtistAssignRepository) AssignArtistToAlbum(ctx context.Context, artistID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, artistID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for AssignArtistToAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, artistID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignRepository_AssignArtistToAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignArtistToAlbum'
type ArtistAssignRepository_AssignArtistToAlbum_Call struct {
	*mock.Call
}

// AssignArtistToAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
//   - albumID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) AssignArtistToAlbum(ctx interface{}, artistID interface{}, albumID interface{}) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	return &ArtistAssignRepository_AssignArtistToAlbum_Call{Call: _e.mock.On("AssignArtistToAlbum", ctx, artistID, albumID)}
}

func (_c *ArtistAssignRepository_AssignArtistToAlbum_Call) Run(run func(ctx context.Context, artistID uuid.UUID, albumID uuid.UUID)) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToAlbum_Call) Return(_a0 error) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// AssignArtistToTrack provides a mock function with given fields: ctx, artistID, trackID
func (_m *ArtistAssignRepository) AssignArtistToTrack(ctx context.Context, artistID uuid.UUID, trackID uuid.UUID) error {
	ret := _m.Called(ctx, artistID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for AssignArtistToTrack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, artistID, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignRepository_AssignArtistToTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignArtistToTrack'
type ArtistAssignRepository_AssignArtistToTrack_Call struct {
	*mock.Call
}

// AssignArtistToTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
//   - trackID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) AssignArtistToTrack(ctx interface{}, artistID interface{}, trackID interface{}) *ArtistAssignRepository_AssignArtistToTrack_Call {
	return &ArtistAssignRepository_AssignArtistToTrack_Call{Call: _e.mock.On("AssignArtistToTrack", ctx, artistID, trackID)}
}

func (_c *ArtistAssignRepository_AssignArtistToTrack_Call) Run(run func(ctx context.Context, artistID uuid.UUID, trackID uuid.UUID)) *ArtistAssignRepository_AssignArtistToTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToTrack_Call) Return(_a0 error) *ArtistAssignRepository_AssignArtistToTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToTrack_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ArtistAssignRepository_AssignArtistToTrack_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtistAssignRepository creates a new instance of ArtistAssignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistAssignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistAssignRepository {
	mock := &ArtistAssignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
