// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ArtistAssignRepository is an autogenerated mock type for the ArtistAssignRepository type
type ArtistAssignRepository struct {
	mock.Mock
}

type ArtistAssignRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtistAssignRepository) EXPECT() *ArtistAssignRepository_Expecter {
	return &ArtistAssignRepository_Expecter{mock: &_m.Mock}
}

// AssignArtistToAlbum provides a mock function with given fields: ctx, artistID, albumID
func (_m *ArtistAssignRepository) AssignArtistToAlbum(ctx context.Context, artistID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, artistID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for AssignArtistToAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, artistID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignRepository_AssignArtistToAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignArtistToAlbum'
type ArtistAssignRepository_AssignArtistToAlbum_Call struct {
	*mock.Call
}

// AssignArtistToAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
//   - albumID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) AssignArtistToAlbum(ctx interface{}, artistID interface{}, albumID interface{}) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	return &ArtistAssignRepository_AssignArtistToAlbum_Call{Call: _e.mock.On("AssignArtistToAlbum", ctx, artistID, albumID)}
}

func (_c *ArtistAssignRepository_AssignArtistToAlbum_Call) Run(run func(ctx context.Context, artistID uuid.UUID, albumID uuid.UUID)) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToAlbum_Call) Return(_a0 error) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ArtistAssignRepository_AssignArtistToAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// AssignArtistToTrack provides a mock function with given fields: ctx, artistID, trackID
func (_m *ArtistAssignRepository) AssignArtistToTrack(ctx context.Context, artistID uuid.UUID, trackID uuid.UUID) error {
	ret := _m.Called(ctx, artistID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for AssignArtistToTrack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, artistID, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignRepository_AssignArtistToTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignArtistToTrack'
type ArtistAssignRepository_AssignArtistToTrack_Call struct {
	*mock.Call
}

// AssignArtistToTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
//   - trackID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) AssignArtistToTrack(ctx interface{}, artistID interface{}, trackID interface{}) *ArtistAssignRepository_AssignArtistToTrack_Call {
	return &ArtistAssignRepository_AssignArtistToTrack_Call{Call: _e.mock.On("AssignArtistToTrack", ctx, artistID, trackID)}
}

func (_c *ArtistAssignRepository_AssignArtistToTrack_Call) Run(run func(ctx context.Context, artistID uuid.UUID, trackID uuid.UUID)) *ArtistAssignRepository_AssignArtistToTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToTrack_Call) Return(_a0 error) *ArtistAssignRepository_AssignArtistToTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignRepository_AssignArtistToTrack_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ArtistAssignRepository_AssignArtistToTrack_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtistAlbums provides a mock function with given fields: ctx, artistID
func (_m *ArtistAssignRepository) GetArtistAlbums(ctx context.Context, artistID uuid.UUID) ([]*entity.AlbumMeta, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetArtistAlbums")
	}

	var r0 []*entity.AlbumMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.AlbumMeta, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.AlbumMeta); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistAssignRepository_GetArtistAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtistAlbums'
type ArtistAssignRepository_GetArtistAlbums_Call struct {
	*mock.Call
}

// GetArtistAlbums is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) GetArtistAlbums(ctx interface{}, artistID interface{}) *ArtistAssignRepository_GetArtistAlbums_Call {
	return &ArtistAssignRepository_GetArtistAlbums_Call{Call: _e.mock.On("GetArtistAlbums", ctx, artistID)}
}

func (_c *ArtistAssignRepository_GetArtistAlbums_Call) Run(run func(ctx context.Context, artistID uuid.UUID)) *ArtistAssignRepository_GetArtistAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_GetArtistAlbums_Call) Return(_a0 []*entity.AlbumMeta, _a1 error) *ArtistAssignRepository_GetArtistAlbums_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistAssignRepository_GetArtistAlbums_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.AlbumMeta, error)) *ArtistAssignRepository_GetArtistAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtistTracks provides a mock function with given fields: ctx, artistID
func (_m *ArtistAssignRepository) GetArtistTracks(ctx context.Context, artistID uuid.UUID) ([]*entity.TrackMeta, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetArtistTracks")
	}

	var r0 []*entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TrackMeta, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TrackMeta); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistAssignRepository_GetArtistTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtistTracks'
type ArtistAssignRepository_GetArtistTracks_Call struct {
	*mock.Call
}

// GetArtistTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) GetArtistTracks(ctx interface{}, artistID interface{}) *ArtistAssignRepository_GetArtistTracks_Call {
	return &ArtistAssignRepository_GetArtistTracks_Call{Call: _e.mock.On("GetArtistTracks", ctx, artistID)}
}

func (_c *ArtistAssignRepository_GetArtistTracks_Call) Run(run func(ctx context.Context, artistID uuid.UUID)) *ArtistAssignRepository_GetArtistTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_GetArtistTracks_Call) Return(_a0 []*entity.TrackMeta, _a1 error) *ArtistAssignRepository_GetArtistTracks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistAssignRepository_GetArtistTracks_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.TrackMeta, error)) *ArtistAssignRepository_GetArtistTracks_Call {
	_c.Call.Return(run)
	return _c
}

// UnassignArtistFromAlbum provides a mock function with given fields: ctx, artistID, albumID
func (_m *ArtistAssignRepository) UnassignArtistFromAlbum(ctx context.Context, artistID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, artistID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for UnassignArtistFromAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, artistID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignRepository_UnassignArtistFromAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnassignArtistFromAlbum'
type ArtistAssignRepository_UnassignArtistFromAlbum_Call struct {
	*mock.Call
}

// UnassignArtistFromAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
//   - albumID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) UnassignArtistFromAlbum(ctx interface{}, artistID interface{}, albumID interface{}) *ArtistAssignRepository_UnassignArtistFromAlbum_Call {
	return &ArtistAssignRepository_UnassignArtistFromAlbum_Call{Call: _e.mock.On("UnassignArtistFromAlbum", ctx, artistID, albumID)}
}

func (_c *ArtistAssignRepository_UnassignArtistFromAlbum_Call) Run(run func(ctx context.Context, artistID uuid.UUID, albumID uuid.UUID)) *ArtistAssignRepository_UnassignArtistFromAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_UnassignArtistFromAlbum_Call) Return(_a0 error) *ArtistAssignRepository_UnassignArtistFromAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignRepository_UnassignArtistFromAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ArtistAssignRepository_UnassignArtistFromAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// UnassignArtistFromTrack provides a mock function with given fields: ctx, artistID, trackID
func (_m *ArtistAssignRepository) UnassignArtistFromTrack(ctx context.Context, artistID uuid.UUID, trackID uuid.UUID) error {
	ret := _m.Called(ctx, artistID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for UnassignArtistFromTrack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, artistID, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAssignRepository_UnassignArtistFromTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnassignArtistFromTrack'
type ArtistAssignRepository_UnassignArtistFromTrack_Call struct {
	*mock.Call
}

// UnassignArtistFromTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
//   - trackID uuid.UUID
func (_e *ArtistAssignRepository_Expecter) UnassignArtistFromTrack(ctx interface{}, artistID interface{}, trackID interface{}) *ArtistAssignRepository_UnassignArtistFromTrack_Call {
	return &ArtistAssignRepository_UnassignArtistFromTrack_Call{Call: _e.mock.On("UnassignArtistFromTrack", ctx, artistID, trackID)}
}

func (_c *ArtistAssignRepository_UnassignArtistFromTrack_Call) Run(run func(ctx context.Context, artistID uuid.UUID, trackID uuid.UUID)) *ArtistAssignRepository_UnassignArtistFromTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAssignRepository_UnassignArtistFromTrack_Call) Return(_a0 error) *ArtistAssignRepository_UnassignArtistFromTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAssignRepository_UnassignArtistFromTrack_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ArtistAssignRepository_UnassignArtistFromTrack_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtistAssignRepository creates a new instance of ArtistAssignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistAssignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistAssignRepository {
	mock := &ArtistAssignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
