// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// FavoritesDeletionService is an autogenerated mock type for the FavoritesDeletionService type
type FavoritesDeletionService struct {
	mock.Mock
}

type FavoritesDeletionService_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoritesDeletionService) EXPECT() *FavoritesDeletionService_Expecter {
	return &FavoritesDeletionService_Expecter{mock: &_m.Mock}
}

// DeletePlaylistFromAllFavorites provides a mock function with given fields: ctx, claims, playlistID
func (_m *FavoritesDeletionService) DeletePlaylistFromAllFavorites(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlaylistFromAllFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlaylistFromAllFavorites'
type FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call struct {
	*mock.Call
}

// DeletePlaylistFromAllFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *FavoritesDeletionService_Expecter) DeletePlaylistFromAllFavorites(ctx interface{}, claims interface{}, playlistID interface{}) *FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call {
	return &FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call{Call: _e.mock.On("DeletePlaylistFromAllFavorites", ctx, claims, playlistID)}
}

func (_c *FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call) Return(_a0 error) *FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *FavoritesDeletionService_DeletePlaylistFromAllFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithFavoritePlaylist provides a mock function with given fields: ctx, claims, playlistID
func (_m *FavoritesDeletionService) GetUsersWithFavoritePlaylist(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithFavoritePlaylist")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithFavoritePlaylist'
type FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call struct {
	*mock.Call
}

// GetUsersWithFavoritePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *FavoritesDeletionService_Expecter) GetUsersWithFavoritePlaylist(ctx interface{}, claims interface{}, playlistID interface{}) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	return &FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call{Call: _e.mock.On("GetUsersWithFavoritePlaylist", ctx, claims, playlistID)}
}

func (_c *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call) Return(_a0 []uuid.UUID, _a1 error) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) ([]uuid.UUID, error)) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreAllFavorites provides a mock function with given fields: ctx, claims, userIDs, playlistID
func (_m *FavoritesDeletionService) RestoreAllFavorites(ctx context.Context, claims *entity.Claims, userIDs []uuid.UUID, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, userIDs, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreAllFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, []uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, userIDs, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoritesDeletionService_RestoreAllFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreAllFavorites'
type FavoritesDeletionService_RestoreAllFavorites_Call struct {
	*mock.Call
}

// RestoreAllFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - userIDs []uuid.UUID
//   - playlistID uuid.UUID
func (_e *FavoritesDeletionService_Expecter) RestoreAllFavorites(ctx interface{}, claims interface{}, userIDs interface{}, playlistID interface{}) *FavoritesDeletionService_RestoreAllFavorites_Call {
	return &FavoritesDeletionService_RestoreAllFavorites_Call{Call: _e.mock.On("RestoreAllFavorites", ctx, claims, userIDs, playlistID)}
}

func (_c *FavoritesDeletionService_RestoreAllFavorites_Call) Run(run func(ctx context.Context, claims *entity.Claims, userIDs []uuid.UUID, playlistID uuid.UUID)) *FavoritesDeletionService_RestoreAllFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].([]uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *FavoritesDeletionService_RestoreAllFavorites_Call) Return(_a0 error) *FavoritesDeletionService_RestoreAllFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoritesDeletionService_RestoreAllFavorites_Call) RunAndReturn(run func(context.Context, *entity.Claims, []uuid.UUID, uuid.UUID) error) *FavoritesDeletionService_RestoreAllFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// NewFavoritesDeletionService creates a new instance of FavoritesDeletionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoritesDeletionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoritesDeletionService {
	mock := &FavoritesDeletionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
