// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GenreRepository is an autogenerated mock type for the GenreRepository type
type GenreRepository struct {
	mock.Mock
}

type GenreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GenreRepository) EXPECT() *GenreRepository_Expecter {
	return &GenreRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *GenreRepository) Create(ctx context.Context, _a1 *entity.Genre) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Genre) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type GenreRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Genre
func (_e *GenreRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *GenreRepository_Create_Call {
	return &GenreRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *GenreRepository_Create_Call) Run(run func(ctx context.Context, _a1 *entity.Genre)) *GenreRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Genre))
	})
	return _c
}

func (_c *GenreRepository_Create_Call) Return(_a0 error) *GenreRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Genre) error) *GenreRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, genreID
func (_m *GenreRepository) Delete(ctx context.Context, genreID uuid.UUID) error {
	ret := _m.Called(ctx, genreID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, genreID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type GenreRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - genreID uuid.UUID
func (_e *GenreRepository_Expecter) Delete(ctx interface{}, genreID interface{}) *GenreRepository_Delete_Call {
	return &GenreRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, genreID)}
}

func (_c *GenreRepository_Delete_Call) Run(run func(ctx context.Context, genreID uuid.UUID)) *GenreRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GenreRepository_Delete_Call) Return(_a0 error) *GenreRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *GenreRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, genreID
func (_m *GenreRepository) Get(ctx context.Context, genreID uuid.UUID) (*entity.Genre, error) {
	ret := _m.Called(ctx, genreID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Genre, error)); ok {
		return rf(ctx, genreID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Genre); ok {
		r0 = rf(ctx, genreID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, genreID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenreRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GenreRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - genreID uuid.UUID
func (_e *GenreRepository_Expecter) Get(ctx interface{}, genreID interface{}) *GenreRepository_Get_Call {
	return &GenreRepository_Get_Call{Call: _e.mock.On("Get", ctx, genreID)}
}

func (_c *GenreRepository_Get_Call) Run(run func(ctx context.Context, genreID uuid.UUID)) *GenreRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GenreRepository_Get_Call) Return(_a0 *entity.Genre, _a1 error) *GenreRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GenreRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Genre, error)) *GenreRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *GenreRepository) Update(ctx context.Context, _a1 *entity.Genre) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Genre) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GenreRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Genre
func (_e *GenreRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *GenreRepository_Update_Call {
	return &GenreRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *GenreRepository_Update_Call) Run(run func(ctx context.Context, _a1 *entity.Genre)) *GenreRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Genre))
	})
	return _c
}

func (_c *GenreRepository_Update_Call) Return(_a0 error) *GenreRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Genre) error) *GenreRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenreRepository creates a new instance of GenreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenreRepository {
	mock := &GenreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
