// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ListeningStatService is an autogenerated mock type for the ListeningStatService type
type ListeningStatService struct {
	mock.Mock
}

type ListeningStatService_Expecter struct {
	mock *mock.Mock
}

func (_m *ListeningStatService) EXPECT() *ListeningStatService_Expecter {
	return &ListeningStatService_Expecter{mock: &_m.Mock}
}

// GetTrackSegments provides a mock function with given fields: ctx, trackID
func (_m *ListeningStatService) GetTrackSegments(ctx context.Context, trackID uuid.UUID) ([]*entity.Segment, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackSegments")
	}

	var r0 []*entity.Segment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Segment, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Segment); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Segment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListeningStatService_GetTrackSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackSegments'
type ListeningStatService_GetTrackSegments_Call struct {
	*mock.Call
}

// GetTrackSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *ListeningStatService_Expecter) GetTrackSegments(ctx interface{}, trackID interface{}) *ListeningStatService_GetTrackSegments_Call {
	return &ListeningStatService_GetTrackSegments_Call{Call: _e.mock.On("GetTrackSegments", ctx, trackID)}
}

func (_c *ListeningStatService_GetTrackSegments_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *ListeningStatService_GetTrackSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ListeningStatService_GetTrackSegments_Call) Return(_a0 []*entity.Segment, _a1 error) *ListeningStatService_GetTrackSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListeningStatService_GetTrackSegments_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Segment, error)) *ListeningStatService_GetTrackSegments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStat provides a mock function with given fields: ctx, event
func (_m *ListeningStatService) UpdateStat(ctx context.Context, event *entity.ListeningEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ListeningEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListeningStatService_UpdateStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStat'
type ListeningStatService_UpdateStat_Call struct {
	*mock.Call
}

// UpdateStat is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.ListeningEvent
func (_e *ListeningStatService_Expecter) UpdateStat(ctx interface{}, event interface{}) *ListeningStatService_UpdateStat_Call {
	return &ListeningStatService_UpdateStat_Call{Call: _e.mock.On("UpdateStat", ctx, event)}
}

func (_c *ListeningStatService_UpdateStat_Call) Run(run func(ctx context.Context, event *entity.ListeningEvent)) *ListeningStatService_UpdateStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ListeningEvent))
	})
	return _c
}

func (_c *ListeningStatService_UpdateStat_Call) Return(_a0 error) *ListeningStatService_UpdateStat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ListeningStatService_UpdateStat_Call) RunAndReturn(run func(context.Context, *entity.ListeningEvent) error) *ListeningStatService_UpdateStat_Call {
	_c.Call.Return(run)
	return _c
}

// NewListeningStatService creates a new instance of ListeningStatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListeningStatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListeningStatService {
	mock := &ListeningStatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
