// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	access_meta "github.com/hahaclassic/orpheon/backend/internal/repository/content/playlist/access-meta/with-cache"
	mock "github.com/stretchr/testify/mock"
)

// OptionFunc is an autogenerated mock type for the OptionFunc type
type OptionFunc struct {
	mock.Mock
}

type OptionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *OptionFunc) EXPECT() *OptionFunc_Expecter {
	return &OptionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *OptionFunc) Execute(_a0 *access_meta.PlaylistAccessRepoWithCache) {
	_m.Called(_a0)
}

// OptionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type OptionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *access_meta.PlaylistAccessRepoWithCache
func (_e *OptionFunc_Expecter) Execute(_a0 interface{}) *OptionFunc_Execute_Call {
	return &OptionFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *OptionFunc_Execute_Call) Run(run func(_a0 *access_meta.PlaylistAccessRepoWithCache)) *OptionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*access_meta.PlaylistAccessRepoWithCache))
	})
	return _c
}

func (_c *OptionFunc_Execute_Call) Return() *OptionFunc_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *OptionFunc_Execute_Call) RunAndReturn(run func(*access_meta.PlaylistAccessRepoWithCache)) *OptionFunc_Execute_Call {
	_c.Run(run)
	return _c
}

// NewOptionFunc creates a new instance of OptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *OptionFunc {
	mock := &OptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
