// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistFavoriteRepository is an autogenerated mock type for the PlaylistFavoriteRepository type
type PlaylistFavoriteRepository struct {
	mock.Mock
}

type PlaylistFavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistFavoriteRepository) EXPECT() *PlaylistFavoriteRepository_Expecter {
	return &PlaylistFavoriteRepository_Expecter{mock: &_m.Mock}
}

// AddToFavorites provides a mock function with given fields: ctx, userID, playlistID
func (_m *PlaylistFavoriteRepository) AddToFavorites(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, userID, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for AddToFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteRepository_AddToFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToFavorites'
type PlaylistFavoriteRepository_AddToFavorites_Call struct {
	*mock.Call
}

// AddToFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) AddToFavorites(ctx interface{}, userID interface{}, playlistID interface{}) *PlaylistFavoriteRepository_AddToFavorites_Call {
	return &PlaylistFavoriteRepository_AddToFavorites_Call{Call: _e.mock.On("AddToFavorites", ctx, userID, playlistID)}
}

func (_c *PlaylistFavoriteRepository_AddToFavorites_Call) Run(run func(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID)) *PlaylistFavoriteRepository_AddToFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_AddToFavorites_Call) Return(_a0 error) *PlaylistFavoriteRepository_AddToFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteRepository_AddToFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *PlaylistFavoriteRepository_AddToFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// GetFavoritePlaylists provides a mock function with given fields: ctx, userID
func (_m *PlaylistFavoriteRepository) GetFavoritePlaylists(ctx context.Context, userID uuid.UUID) ([]*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFavoritePlaylists")
	}

	var r0 []*entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.PlaylistMeta, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.PlaylistMeta); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistFavoriteRepository_GetFavoritePlaylists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavoritePlaylists'
type PlaylistFavoriteRepository_GetFavoritePlaylists_Call struct {
	*mock.Call
}

// GetFavoritePlaylists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) GetFavoritePlaylists(ctx interface{}, userID interface{}) *PlaylistFavoriteRepository_GetFavoritePlaylists_Call {
	return &PlaylistFavoriteRepository_GetFavoritePlaylists_Call{Call: _e.mock.On("GetFavoritePlaylists", ctx, userID)}
}

func (_c *PlaylistFavoriteRepository_GetFavoritePlaylists_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *PlaylistFavoriteRepository_GetFavoritePlaylists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_GetFavoritePlaylists_Call) Return(_a0 []*entity.PlaylistMeta, _a1 error) *PlaylistFavoriteRepository_GetFavoritePlaylists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistFavoriteRepository_GetFavoritePlaylists_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.PlaylistMeta, error)) *PlaylistFavoriteRepository_GetFavoritePlaylists_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithFavoritePlaylist provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistFavoriteRepository) GetUsersWithFavoritePlaylist(ctx context.Context, playlistID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithFavoritePlaylist")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithFavoritePlaylist'
type PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call struct {
	*mock.Call
}

// GetUsersWithFavoritePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) GetUsersWithFavoritePlaylist(ctx interface{}, playlistID interface{}) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	return &PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call{Call: _e.mock.On("GetUsersWithFavoritePlaylist", ctx, playlistID)}
}

func (_c *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call) Return(_a0 []uuid.UUID, _a1 error) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromFavorites provides a mock function with given fields: ctx, userID, playlistID
func (_m *PlaylistFavoriteRepository) RemoveFromFavorites(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, userID, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteRepository_RemoveFromFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromFavorites'
type PlaylistFavoriteRepository_RemoveFromFavorites_Call struct {
	*mock.Call
}

// RemoveFromFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) RemoveFromFavorites(ctx interface{}, userID interface{}, playlistID interface{}) *PlaylistFavoriteRepository_RemoveFromFavorites_Call {
	return &PlaylistFavoriteRepository_RemoveFromFavorites_Call{Call: _e.mock.On("RemoveFromFavorites", ctx, userID, playlistID)}
}

func (_c *PlaylistFavoriteRepository_RemoveFromFavorites_Call) Run(run func(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID)) *PlaylistFavoriteRepository_RemoveFromFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_RemoveFromFavorites_Call) Return(_a0 error) *PlaylistFavoriteRepository_RemoveFromFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteRepository_RemoveFromFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *PlaylistFavoriteRepository_RemoveFromFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePlaylistFromAllFavorites provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistFavoriteRepository) RemovePlaylistFromAllFavorites(ctx context.Context, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePlaylistFromAllFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePlaylistFromAllFavorites'
type PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call struct {
	*mock.Call
}

// RemovePlaylistFromAllFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) RemovePlaylistFromAllFavorites(ctx interface{}, playlistID interface{}) *PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call {
	return &PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call{Call: _e.mock.On("RemovePlaylistFromAllFavorites", ctx, playlistID)}
}

func (_c *PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call) Return(_a0 error) *PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PlaylistFavoriteRepository_RemovePlaylistFromAllFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistFavoriteRepository creates a new instance of PlaylistFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistFavoriteRepository {
	mock := &PlaylistFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
