// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TrackDeleter is an autogenerated mock type for the TrackDeleter type
type TrackDeleter struct {
	mock.Mock
}

type TrackDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *TrackDeleter) EXPECT() *TrackDeleter_Expecter {
	return &TrackDeleter_Expecter{mock: &_m.Mock}
}

// DeleteTrack provides a mock function with given fields: ctx, claims, trackID
func (_m *TrackDeleter) DeleteTrack(ctx context.Context, claims *entity.Claims, trackID uuid.UUID) error {
	ret := _m.Called(ctx, claims, trackID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackDeleter_DeleteTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrack'
type TrackDeleter_DeleteTrack_Call struct {
	*mock.Call
}

// DeleteTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - trackID uuid.UUID
func (_e *TrackDeleter_Expecter) DeleteTrack(ctx interface{}, claims interface{}, trackID interface{}) *TrackDeleter_DeleteTrack_Call {
	return &TrackDeleter_DeleteTrack_Call{Call: _e.mock.On("DeleteTrack", ctx, claims, trackID)}
}

func (_c *TrackDeleter_DeleteTrack_Call) Run(run func(ctx context.Context, claims *entity.Claims, trackID uuid.UUID)) *TrackDeleter_DeleteTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TrackDeleter_DeleteTrack_Call) Return(_a0 error) *TrackDeleter_DeleteTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackDeleter_DeleteTrack_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *TrackDeleter_DeleteTrack_Call {
	_c.Call.Return(run)
	return _c
}

// NewTrackDeleter creates a new instance of TrackDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackDeleter {
	mock := &TrackDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
