services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ../infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../infra/nginx/conf.d:/etc/nginx/conf.d
      - ../infra/nginx/static:/etc/nginx/static:ro
      - legacy_frontend_dist:/usr/share/nginx/html/legacy
    depends_on:
      - auth-msv
      - auth-msv-ro
      # - auth-msv-ro-2
      - user-msv
      - user-msv-ro
      # - user-msv-ro2
      # - user-msv-ro-2
      - content-msv
      - content-msv-ro
      # - content-msv-ro-2
      - pgadmin
      - grafana
      - swagger-ui
      - legacy-frontend
    networks:
      - backend
    restart: unless-stopped

  auth-msv:
    build:
      context: ../services/auth-msv
      dockerfile: Dockerfile
    environment:
      - READ_ONLY=false
      - USER_CREATOR_HOST=user-msv
      - POSTGRES_HOST=postgres-primary
    env_file:
      - ../.config/.auth.env
    expose:
      - "8080"
    depends_on:
      postgres-primary:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-msv:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped
    labels:
      - "logging=promtail"

  auth-msv-ro:
    build:
      context: ../services/auth-msv
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - READ_ONLY=true
      - USER_CREATOR_HOST=user-msv
      - POSTGRES_HOST=postgres-replica
    env_file:
      - ../.config/.auth.env
    expose:
      - "8080"
    depends_on:
      postgres-replica:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-msv:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped
    labels:
      - "logging=promtail"

  # auth-msv-ro-2:
  #   build:
  #     context: ../services/auth-msv
  #     dockerfile: Dockerfile
  #   container_name: orpheon-auth-msv-ro-2
  #   # deploy:
  #   #   replicas: 2
  #   environment:
  #     - HOST=auth-msv-ro-2
  #     - READ_ONLY=true
  #     - USER_CREATOR_HOST=user-msv
  #   env_file:
  #     - ../.config/.auth.env
  #   expose:
  #     - "8080"
  #   depends_on:
  #     postgres-replica:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     user-msv:
  #       condition: service_started
  #   networks:
  #     - backend

  user-msv:
    build:
      context: ../services/user-msv
      dockerfile: Dockerfile
    # container_name: user-msv
    environment:
      - HTTP_PORT=8080
      - READ_ONLY=false
      - POSTGRES_HOST=postgres-primary
    env_file:
      - ../.config/.user.env
    expose:
      - "8080"
      - "50051"
    depends_on:
      postgres-primary:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped
    labels:
      - "logging=promtail"

  user-msv-ro:
    build:
      context: ../services/user-msv
      dockerfile: Dockerfile
    # container_name: user-msv-ro1
    deploy:
      replicas: 2
    environment:
      - HTTP_PORT=8080
      - READ_ONLY=true
      - POSTGRES_HOST=postgres-replica
    env_file:
      - ../.config/.user.env
    expose:
      - "8080"
      - "50051"
    depends_on:
      postgres-replica:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped
    labels:
      - "logging=promtail"

  # user-msv-ro2:
  #   build:
  #     context: ../services/user-msv
  #     dockerfile: Dockerfile
  #   container_name: user-msv-ro2
  #   # deploy:
  #   #   replicas: 2
  #   environment:
  #     - HTTP_PORT=8082
  #     - READ_ONLY=true
  #   env_file:
  #     - ../.config/.user.env
  #   expose:
  #     - "8082"
  #     - "50051"
  #   depends_on:
  #     postgres-replica:
  #       condition: service_healthy
  #   networks:
  #     - backend

  content-msv:
    build:
      context: ../services/content-msv
      dockerfile: Dockerfile
    environment:
      - READ_ONLY=false
      - USER_INFO_HOST=user-msv
      - POSTGRES_HOST=postgres-primary
    env_file:
      - ../.config/.content.env
    expose:
      - "8080"
    depends_on:
      postgres-primary:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
      user-msv:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped
    labels:
      - "logging=promtail"

  content-msv-ro:
    build:
      context: ../services/content-msv
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - READ_ONLY=true
      - USER_INFO_HOST=user-msv-ro
      - POSTGRES_HOST=postgres-replica
    env_file:
      - ../.config/.content.env
    expose:
      - "8080"
    depends_on:
      postgres-replica:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
      user-msv-ro:
        condition: service_started
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "logging=promtail"
  
  # content-msv-ro-2:
  #   build:
  #     context: ../services/content-msv
  #     dockerfile: Dockerfile
  #   container_name: orpheon-content-msv-ro-2
  #   # deploy:
  #   #   replicas: 2
  #   environment:
  #     - HOST=content-msv-ro-2
  #     - READ_ONLY=true
  #     - USER_INFO_HOST=user-msv-ro-2
  #   env_file:
  #     - ../.config/.content.env
  #   expose:
  #     - "8080"
  #   depends_on:
  #     postgres-replica:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     minio:
  #       condition: service_started
  #     user-msv-ro-2:
  #       condition: service_started
  #   networks:
  #     - backend
