
server {
    listen 80;
    server_name localhost;

    server_tokens off;                
    add_header Server "Orpheon";

    proxy_cache public_api;
    proxy_cache_key "$scheme$request_method$host$request_uri";
    add_header X-Cache-Status $upstream_cache_status;
    proxy_no_cache $cache_get_only = 0;
    proxy_cache_bypass $cache_get_only = 0;

    root /etc/nginx/static;

    set $mirror "";
    if ($request_uri ~ ^/mirror/) {
        set $mirror "_mirror";
        
        # Delete /mirror from URL
        rewrite ^/mirror(.*) $1 break;
    }

    include /etc/nginx/conf.d/locations/*.conf;
}
