
server {
    listen 80;
    server_name localhost;

    server_tokens off;                
    add_header Server "Orpheon";

    root /etc/nginx/static;

    set $mirror "";
    if ($request_uri ~ ^/mirror/) {
        set $mirror "_mirror";
        
        # Delete /mirror from URL
        rewrite ^/mirror(.*) $1 break;
    }

    include /etc/nginx/conf.d/proxy/cache.conf;
    include /etc/nginx/conf.d/locations/*.conf;
}
