# upstream auth_msv {
#     least_conn;
#     server auth-msv:8080 weight=2;
#     server auth-msv:8080;
#     server auth-msv:8080;
# }

# upstream api_rw {
#     server content-msv:8080;
# }

# upstream api_ro {
#     server content-msv:8081 weight=2;
#     server content-msv:8082;
#     server content-msv:8083;
# }
