# MAIN
upstream auth_msv_get {
    server orpheon-auth-msv-1:8080 weight=2;
    server orpheon-auth-msv-ro-1:8080 weight=1;
    server orpheon-auth-msv-ro-2:8080 weight=1;
}

upstream auth_msv {
    server orpheon-auth-msv-1:8080;
}

upstream user_msv_get {
    server orpheon-user-msv-1:8080 weight=2;
    server orpheon-user-msv-ro-1:8080;
    server orpheon-user-msv-ro-2:8080;
}

upstream user_msv {
    server user-msv:8080;
}

upstream content_msv_get {
    server orpheon-content-msv-1:8080 weight=2;
    server orpheon-content-msv-ro-1:8080 weight=1;
    server orpheon-content-msv-ro-2:8080 weight=1;
}

upstream content_msv {
    server orpheon-content-msv-1:8080;
}

# MIRROR
upstream auth_msv_get_mirror {
    server orpheon-auth-msv-mirror-1:8080 weight=2;
    server orpheon-auth-msv-ro-mirror-1:8080 weight=1;
    server orpheon-auth-msv-ro-mirror-2:8080 weight=1;
}

upstream auth_msv_mirror {
    server orpheon-auth-msv-mirror-1:8080;
}

upstream user_msv_get_mirror {
    server orpheon-user-msv-mirror-1:8080 weight=2;
    server orpheon-user-msv-ro-mirror-1:8080 weight=1;
    server orpheon-user-msv-ro-mirror-2:8080 weight=1;
}

upstream user_msv_mirror {
    server orpheon-user-msv-mirror-1:8080;
}

upstream content_msv_get_mirror {
    server orpheon-content-msv-mirror-1:8080 weight=2;
    server orpheon-content-msv-ro-mirror-1:8080 weight=1;
    server orpheon-content-msv-ro-mirror-2:8080 weight=1;
}

upstream content_msv_mirror {
    server orpheon-content-msv-mirror-1:8080;
}

map $upstream_addr $upstream_server_name {
    hostnames;
    
    orpheon-auth-msv-1:8080          "auth-msv-primary";
    orpheon-auth-msv-ro-1:8080       "auth-msv-replica-1";
    orpheon-auth-msv-ro-2:8080       "auth-msv-replica-2";

    orpheon-user-msv-1:8080            "user-msv-primary";
    orpheon-user-msv-ro-1:8080       "user-msv-replica-1";
    orpheon-user-msv-ro-2:8080       "user-msv-replica-2";

    orpheon-content-msv-1:8080         "content-msv-primary";
    orpheon-content-msv-ro-1:8080    "content-msv-replica-1";
    orpheon-content-msv-ro-2:8080    "content-msv-replica-2";

    default                  $upstream_addr;
}

upstream swagger_ui {
    server orpheon-swagger-ui-1:8080;
}