syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "jwt/v1/proto/jwt.proto";

option go_package = "github.com/hahaclassic/orpheon/api/user-msv/v1/proto";

package user.v1;

service UserService {
    rpc GetUser(GetUserRequest) returns (User);
    rpc UpdateUser(UpdateUserRequest) returns (google.protobuf.Empty);
    rpc DeleteUser(DeleteUserRequest) returns (google.protobuf.Empty);
}

enum AccessLevel {
    UNKNOWN = 0;
    USER = 1;
    ADMIN = 2;
}

message User {
    string id = 1;
    string name = 2;
    AccessLevel access_level = 3;
    google.protobuf.Timestamp registration_date = 4;
}

message UpdateUserRequest {
    User user = 1;
    jwt.Claims claims = 2;
}

message DeleteUserRequest {
    string user_id = 1;
    jwt.Claims claims = 2;
}

message GetUserRequest {
    string user_id = 1;
}
