// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: user-msv/v1/proto/user.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	proto "github.com/hahaclassic/orpheon/api/jwt/v1/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessLevel int32

const (
	AccessLevel_UNKNOWN AccessLevel = 0
	AccessLevel_USER    AccessLevel = 1
	AccessLevel_ADMIN   AccessLevel = 2
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER",
		2: "ADMIN",
	}
	AccessLevel_value = map[string]int32{
		"UNKNOWN": 0,
		"USER":    1,
		"ADMIN":   2,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_user_msv_v1_proto_user_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_user_msv_v1_proto_user_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_user_msv_v1_proto_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccessLevel      AccessLevel            `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3,enum=user.v1.AccessLevel" json:"access_level,omitempty"`
	RegistrationDate *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_msv_v1_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_UNKNOWN
}

func (x *User) GetRegistrationDate() *timestamp.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_msv_v1_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Claims        *proto.Claims          `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_msv_v1_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetClaims() *proto.Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Claims        *proto.Claims          `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_msv_v1_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserRequest) GetClaims() *proto.Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_msv_v1_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_msv_v1_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_user_msv_v1_proto_user_proto protoreflect.FileDescriptor

const file_user_msv_v1_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1cuser-msv/v1/proto/user.proto\x12\auser.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16jwt/v1/proto/jwt.proto\"\xac\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\faccess_level\x18\x03 \x01(\x0e2\x14.user.v1.AccessLevelR\vaccessLevel\x12G\n" +
	"\x11registration_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10registrationDate\"/\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"[\n" +
	"\x11UpdateUserRequest\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12#\n" +
	"\x06claims\x18\x02 \x01(\v2\v.jwt.ClaimsR\x06claims\"Q\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\x06claims\x18\x02 \x01(\v2\v.jwt.ClaimsR\x06claims\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId*/\n" +
	"\vAccessLevel\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x022\xfd\x01\n" +
	"\vUserService\x127\n" +
	"\n" +
	"CreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\r.user.v1.User\x121\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\r.user.v1.User\x12@\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteUser\x12\x1a.user.v1.DeleteUserRequest\x1a\x16.google.protobuf.EmptyB6Z4github.com/hahaclassic/orpheon/api/user-msv/v1/protob\x06proto3"

var (
	file_user_msv_v1_proto_user_proto_rawDescOnce sync.Once
	file_user_msv_v1_proto_user_proto_rawDescData []byte
)

func file_user_msv_v1_proto_user_proto_rawDescGZIP() []byte {
	file_user_msv_v1_proto_user_proto_rawDescOnce.Do(func() {
		file_user_msv_v1_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_msv_v1_proto_user_proto_rawDesc), len(file_user_msv_v1_proto_user_proto_rawDesc)))
	})
	return file_user_msv_v1_proto_user_proto_rawDescData
}

var file_user_msv_v1_proto_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_msv_v1_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_msv_v1_proto_user_proto_goTypes = []any{
	(AccessLevel)(0),            // 0: user.v1.AccessLevel
	(*User)(nil),                // 1: user.v1.User
	(*CreateUserRequest)(nil),   // 2: user.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),   // 3: user.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),   // 4: user.v1.DeleteUserRequest
	(*GetUserRequest)(nil),      // 5: user.v1.GetUserRequest
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*proto.Claims)(nil),        // 7: jwt.Claims
	(*empty.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_user_msv_v1_proto_user_proto_depIdxs = []int32{
	0, // 0: user.v1.User.access_level:type_name -> user.v1.AccessLevel
	6, // 1: user.v1.User.registration_date:type_name -> google.protobuf.Timestamp
	1, // 2: user.v1.UpdateUserRequest.user:type_name -> user.v1.User
	7, // 3: user.v1.UpdateUserRequest.claims:type_name -> jwt.Claims
	7, // 4: user.v1.DeleteUserRequest.claims:type_name -> jwt.Claims
	2, // 5: user.v1.UserService.CreateUser:input_type -> user.v1.CreateUserRequest
	5, // 6: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	3, // 7: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	4, // 8: user.v1.UserService.DeleteUser:input_type -> user.v1.DeleteUserRequest
	1, // 9: user.v1.UserService.CreateUser:output_type -> user.v1.User
	1, // 10: user.v1.UserService.GetUser:output_type -> user.v1.User
	8, // 11: user.v1.UserService.UpdateUser:output_type -> google.protobuf.Empty
	8, // 12: user.v1.UserService.DeleteUser:output_type -> google.protobuf.Empty
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_user_msv_v1_proto_user_proto_init() }
func file_user_msv_v1_proto_user_proto_init() {
	if File_user_msv_v1_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_msv_v1_proto_user_proto_rawDesc), len(file_user_msv_v1_proto_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_msv_v1_proto_user_proto_goTypes,
		DependencyIndexes: file_user_msv_v1_proto_user_proto_depIdxs,
		EnumInfos:         file_user_msv_v1_proto_user_proto_enumTypes,
		MessageInfos:      file_user_msv_v1_proto_user_proto_msgTypes,
	}.Build()
	File_user_msv_v1_proto_user_proto = out.File
	file_user_msv_v1_proto_user_proto_goTypes = nil
	file_user_msv_v1_proto_user_proto_depIdxs = nil
}
