all: shopcart order auth delivery warehouse

shopcart:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./shopcart-msv/v1/shopcart.proto

order:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./order-msv/v1/order.proto

auth:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./auth-msv/v1/proto/auth.proto

delivery:	
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./delivery-msv/v1/delivery.proto

warehouse:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./warehouse-msv/v1/warehouse.proto

jwt-proto:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./common/jwt/v1/proto/jwt.proto

