all: jwt-proto auth user content streaming

auth:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./auth-msv/v1/proto/auth.proto

user:	
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./user-msv/v1/proto/user.proto

content:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./content-msv/v1/proto/content.proto

streaming:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./streaming-msv/v1/proto/streaming.proto

jwt-proto:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative ./jwt/v1/proto/jwt.proto

