name: Go CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/**'

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
          cache: true

      - name: Create mod cache directory
        run: mkdir -p /home/runner/go/pkg/mod

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies (Go)
        working-directory: backend
        run: go mod tidy

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Run linter
        working-directory: backend
        run: golangci-lint run ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Run unit tests
        working-directory: backend
        run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build
        working-directory: backend
        run: go build -v ./...
