name: Go CI

on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - develop

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Кэширование зависимостей
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Установка зависимостей
        working-directory: backend
        run: go mod tidy

      - name: Установка golangci-lint (последняя версия)
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Проверка кода линтером (golangci-lint)
        working-directory: backend
        run: |
          golangci-lint run ./...

      - name: Сборка проекта
        working-directory: backend
        run: go build -v ./...

      - name: Запуск тестов
        working-directory: backend
        run: go test -v ./...
